spring:
  application:
    name: yuan-ai-agent
  profiles:
    active: local
  # 临时注释掉，便于大家开发调试和部署（实际填写 PgVector 数据库信息）
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&connectTimeout=60&socketTimeout=60
    username: postgres
    password: password
  ai:
    dashscope:
      api-key: ${API-KEY}
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    # 临时注释掉，便于大家开发调试和部署（实际需要启动 PgVector 数据库）
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#        initialize-schema: true
#        schema-name: public
#        table-name: vector_store
#  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yuan?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 2003dhy0915

## MP 配置
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yuan.yuanaiagent.controller

# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    #    org.springframework.ai.chat.advisor.SimpleChatAdvisor: DEBUG
    org.springframework.ai: DEBUG